### ISSUE TITLE
Samples don't run (VS 2015)

### ISSUE THREAD

**Issue by black-snow** [DotNetOpenAuth/DotNetOpenAuth.Samples#22]
I've just downloaded the samples and tried to run *OAuthConsumerWpf* but sadly it doesn't build. After updating the nuget packages I had to manually open pretty much any file for VS to recognize there aren't any errors.

Still there are a couple errors left.

```
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile
Fehler		Package restore is disabled by default. To give consent, open the Visual Studio Options dialog, click on Package Manager node and check 'Allow NuGet to download missing packages during build.' You can also give consent by setting the environment variable 'EnableNuGetPackageRestore' to 'true'.	DotNetOpenAuth.ApplicationBlock		
```

(actually the mentioned option is enabled ...)

```
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile
Fehler		Der Befehl ""C:\Users\developer\Downloads\DotNetOpenAuth.Samples-master\DotNetOpenAuth.Samples-master\.nuget\nuget.exe" install "C:\Users\developer\Downloads\DotNetOpenAuth.Samples-master\DotNetOpenAuth.Samples-master\src\DotNetOpenAuth.ApplicationBlock\packages.config" -source "" -o "C:\Users\developer\Downloads\DotNetOpenAuth.Samples-master\DotNetOpenAuth.Samples-master\packages"" wurde mit dem Code 1 beendet.	DotNetOpenAuth.ApplicationBlock		
```

Also there's a reference to *Microsoft.Contracts* that can't be followed. And it says it can't open *OAuth/OAuth 2/OAuthClient*.

Any guesses?

**Comment by DavidChristiansen** [comment]
Will investigate and advise.

**Comment by black-snow** [comment]
Thanks in advance.

**Comment by tristandavey** [comment]
Hi is there any progress on this? I need to get the Facebook email so added it into the FacebookGraph.cs but can't package it all up to use and get the same error listed above!

**Comment by Zukeh** [comment]
Have the same problem, any update?

Thank you

**Comment by JobaDiniz** [comment]
Couldn't build this... Microsoft.Contracts is missing and nuget:

```
Error	1	The process cannot access the file '..\DotNetOpenAuth.Samples-master\packages\Microsoft.Bcl.Build.1.0.8\tools\Microsoft.Bcl.Build.Tasks.dll' because it is being used by another process.	DotNetOpenAuth.ApplicationBlock

```

**Comment by Yortw** [comment]
Managed to get the code to build by unloading every csproj in the solution except the authorizationserver, then doing a nuget restore on that. Then I reloaded and did a nuget restore on every other project individually. At the end, the code built ok.

I also had an attempt at updating all the packages to their latest versions, but some no longer support .net 4, so that was a bad idea.
